import React from 'react'

const Home = () =>
  <div>
    <div id='home-component'>
      <div id='home-component-background'>
        <h1 className="welcome">Welcome to CSL Online!</h1>
        <br />
        <img className='logo' id='logo' alt='CSL Online logo' src='/img/cslo-logo.png' />
      </div>
    </div>
    <br />
    <div className='row'>
      <div className='col-sm-12'>
        <h3>Scouting Sytem</h3>
      </div>
    </div>
    <div className='row'>
      <h5>Scouting</h5>
      <ol>
        <li>There will be a total of 8 scouting periods, one for each regular season month from November to May and one post-lottery.</li>
        <li>There will be 2 double scouting periods (for up to 20 scouts!) throughout the season: February and post-lottery.</li>
        <li>GMs will have to release either one CSL Insider/two Wiretaps/one hosted Podcast (for 10 scouts) or 1 wiretap/Podcast guest appearance (for 5 scouts) within each period in order to qualify for scouting that month. You must post the link to your article/s in that month's Scouting thread as soon as you submit your scouting file. You do not officially qualify unless you post your link.</li>
        <li>Special requirements may be put in place of regular articles. Please check the schedule to find if there's a special requirement for the period (Season Pre- and Reviews, draft related articles)</li>
        <li>Each qualifying team will have five or eight (5 or 10) scouts available at their disposal. You may deploy your scouts however you want. You can have each of them scout a different player or you can assign 2 or more to scout the same player.</li>
        <li>Your scouts will report on the following categories:</li>
        <ul>
          <li>FGD FGI FGJ FT FG3 DRFL - with +/- 2 points deviation (both current and potential)</li>
          <li>SCR PAS HDL ORB DRB DEF BLK STL DIS IQ - with +/- 5 deviation (current) and +/- 15 deviation (potential)</li>
        </ul>
        <li>The deviation is generated by a program each time. You can scout the same player 10 times and likely come out with 10 different reports. So it may make sense to scout a player more than once. The deviation remains the same and does not guarantee a more accurate report. However, averaging your reports may increase the chance of getting close to their actual rating. Cross-referencing the numbers could also get you closer to the actual rating.</li>
      </ol>
    </div>
    <div className='row'>
      <h5>CSL Combine</h5>
      <ol>
        <li>The CSL combine consists of the Pre-Draft Camp and Interviews. It will take place during the playoffs, after the lottery.</li>
        <li>During the Pre-Draft Camp, prospects are invited to participate in various drills to showcase their skills. Prospects, especially ones whose stock is high, may choose to decline the invite. The camp will reveal the following:</li>
        <ul>
          <li>FGD FGI FGJ FG3 FT DRFL - with +/- 4 points deviation (current only)</li>
          <li>SCR PAS HDL ORB DRB DEF BLK STL DIS IQ - with +/- 10 deviation (current only)</li>
          <li>The larger deviations are designed to emulate the contained and specialized environment of a real life draft combine. It gives you a general idea of the player but it doesn't give you the same information you can get from watching someone perform in real game situations. </li>
        </ul>
        <li>The Pre-Draft Camp will be a public affair (meaning you won't have to do anything). The camp will be simulated and the results will be released in excel (.xls) form.</li>
        <li>The CSL Combine is also the time for teams to request Interviews. For each player you Interview, you will get his rating for the following categories:</li>
        <ul>
          <li>IQ (potential) - true rating </li>
          <li>CON, GRE, LOY, PFW, PT, PER, DUR, WE, POP - with +/- 15 deviation</li>
        </ul>
        <li>You will be allowed as many Interviews as points you earned during the Scouting period. The points you've accumulated will be posted on the Interview submission thread when it opens.</li>
      </ol>
    </div>
    <div className='row'>
      <h5>Workouts</h5>
      <ol>
        <li>Teams will be allowed to workout players after the combine.</li>
        <li>You will be allowed 15 workouts.</li>
        <li>Workouts will reveal the following:</li>
        <ul>
          <li>FGD FGI FGJ FT FG3 DRFL - with +/- 2 points deviation (both current and potential)</li>
          <li>SCR PAS HDL ORB DRB DEF BLK STL DIS IQ - with +/- 5 deviation (current) and +/- 15 deviation (potential)</li>
        </ul>
      </ol>
    </div>
  </div>

  export default Home
